algo: "dreamer"
id: "experiment"
seed: 1
disable_cuda: False
env: "LavaGap"
max_episode_length: 50
experience_size: 10000
cnn_activation_function: "relu"
dense_activation_function: "elu"

embedding_size: 1024
hidden_size: 128
belief_size: 128
state_size: 16
action_repeat: 1
action_noise: 0.25
episodes: 1000
seed_episodes: 5
collect_interval: 100
batch_size: 50
chunk_size: 50
worldmodel_LogProbLoss: False
overshooting_distance: 10
overshooting_kl_beta: 0
overshooting_reward_scale: 0
global_kl_beta: 0
free_nats: 5
model_learning_rate: 0.001
actor_learning_rate: 0.00005
value_learning_rate: 0.00005
learning_rate_schedule: 0
adam_epsilon: 0.000001
grad_clip_norm: 100.0
planning_horizon: 5
discount: 1.0
disclam: 1.0
optimisation_iters: 10
candidates: 1000
top_candidates: 100

test: False
test_interval: 25
test_episodes: 10

checkpoint_interval: 50
checkpoint_experience: False
models: ""

experience_replay: ""
render: False
paths_to_sample: 10
violation_threshold: 3
