algo: "dreamer"
id: "7x7"
seed: 0
disable_cuda: False
env: "LavaGap"
max_episode_length: 50
experience_size: 10000
cnn_activation_function: "relu"
dense_activation_function: "elu"

embedding_size: 128
hidden_size: 1024
belief_size: 256
state_size: 128
action_repeat: 1
action_noise: 0.3
episodes: 150
seed_episodes: 20
collect_interval: 100
batch_size: 50
chunk_size: 50
worldmodel_LogProbLoss: False
overshooting_distance: 15
overshooting_kl_beta: 0
overshooting_reward_scale: 0
global_kl_beta: 0
free_nats: 5
model_learning_rate: 0.0001
actor_learning_rate: 0.00005
value_learning_rate: 0.00005

learning_rate_schedule: 0
adam_epsilon: 0.00001
grad_clip_norm: 100.0
planning_horizon: 10
discount: 0.95
disclam: 0.95
optimisation_iters: 10
candidates: 1000
top_candidates: 100

test: False
test_interval: 20
test_episodes: 5

checkpoint_interval: 50
checkpoint_experience: False
models: ""

experience_replay: ""
render: False
paths_to_sample: 10
violation_threshold: 4
