algo: "dreamer"
id: "multi-violations-v2"
seed: 0
disable_cuda: False

env: "LavaGapS7-Relaxed"
max_episode_length: 50

#############################
#  Training config          #
#############################
experience_size: 5000
cnn_activation_function: "relu"
dense_activation_function: "elu"
actor_distribution: "tanh_normal"

embedding_size: 32
hidden_size: 64
belief_size: 64
state_size: 16
action_repeat: 1
action_noise: 2
action_noise_decay: 0.99995
action_noise_min: 0.5

episodes: 1000
seed_episodes: 5
collect_interval: 50
batch_size: 64
chunk_size: 25

worldmodel_LogProbLoss: False
overshooting_distance: 25
overshooting_kl_beta: 0
overshooting_reward_scale: 0
global_kl_beta: 0
free_nats: 5
model_learning_rate: 0.0001
actor_learning_rate: 0.00001
value_learning_rate: 0.00001
violation_learning_rate: 0.0001

learning_rate_schedule: 0
adam_epsilon: 0.00001
grad_clip_norm: 1.0
planning_horizon: 5
discount: 0.99
disclam: 0.95
optimisation_iters: 10
candidates: 1000
top_candidates: 100

test: False
test_interval: 25
test_episodes: 2

checkpoint_interval: 50
checkpoint_experience: False
models: ""
experience_replay: ""

render: False
paths_to_sample: 10
violation_threshold: 2
