algo: "dreamer"
id: "multi-violations-v4"
seed: 0
disable_cuda: False

env: "LavaGapS7-Relaxed"
max_episode_length: 50

#############################
#  Training config          #
#############################
experience_size: 1000
cnn_activation_function: "relu"
dense_activation_function: "elu"
actor_distribution: "tanh_normal"

embedding_size: 16
hidden_size: 64
belief_size: 32
state_size: 32
action_repeat: 1
action_noise: 2
action_noise_decay: 0.99995
action_noise_min: 0.5
entropy_coefficient: 0.01

episodes: 500
seed_episodes: 15
collect_interval: 20
batch_size: 64
chunk_size: 25

worldmodel_LogProbLoss: False
overshooting_distance: 25
overshooting_kl_beta: 0
overshooting_reward_scale: 0
global_kl_beta: 0
free_nats: 5
model_learning_rate: 0.001
actor_learning_rate: 0.00001
value_learning_rate: 0.00001
violation_learning_rate: 0.00001

learning_rate_schedule: 0
adam_epsilon: 0.000001
grad_clip_norm: 1.0
planning_horizon: 10
discount: 0.95
disclam: 0.95
optimisation_iters: 10
candidates: 1000
top_candidates: 100

test: False
test_interval: 25
test_episodes: 2

checkpoint_interval: 50
checkpoint_experience: False
models: ""
experience_replay: ""

render: False
paths_to_sample: 5
violation_threshold: 10
